name = "rangers-chess"
main = "src/index.ts"
compatibility_date = "2023-06-25"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "rangers-chess"
database_id = "f963b960-414c-42ec-a4e4-81cce0893d08"
